# Generated by Django 4.0.5 on 2022-06-22 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_review_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
    ]
